# Do not modify this file!  It was generated by ‘nixos-generate-config’
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # ═══════════════════════════════════════════════════════════════════════════════
  # KERNEL TUNING
  # ═══════════════════════════════════════════════════════════════════════════════
  boot.kernel.sysctl = {
    "vm.max_map_count" = 16777216;
    "fs.file-max" = 524288;
    "net.core.rmem_max" = 134217728;
    "net.core.wmem_max" = 134217728;
    "net.ipv4.tcp_rmem" = "4096 87380 134217728";
    "net.ipv4.tcp_wmem" = "4096 65536 134217728";
    "net.ipv4.tcp_congestion_control" = "bbr";
  };
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e61c4234-bcd4-4f44-aebc-839a088fb3ee";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/7CC3-45AD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # ═══════════════════════════════════════════════════════════════════════════════
  # FILE SYSTEMS
  # ═══════════════════════════════════════════════════════════════════════════════
  fileSystems."/home/tank/Games" = {
    device = "/dev/disk/by-uuid/bf5ad455-c95d-410c-af93-e67082f722db";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/mnt/samsung-1tb" = {
    device = "/dev/disk/by-uuid/9dcd0554-7354-4754-9707-c9da3a3c0fae";
    fsType = "ext4";
    options = [ "nofail" ];
  };
  swapDevices =
    [{ device = "/dev/disk/by-uuid/907f32a3-f2e7-402d-82ea-3b47adca8a41"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
